In [1]:
!pip install mediapipe opencv-python tensorflow torch

In [2]:
import cv2
import numpy as np
import os
from matplotlib import pyplot as plt
import time
import mediapipe as mp
import torch
# Initialize MediaPipe Hands
mp_hands = mp.solutions.hands
hands = mp_hands.Hands(max_num_hands=1)  # Detecting only one hand
mp_draw = mp.solutions.drawing_utils

In [2]:
import cv2
import mediapipe as mp

# Initialize MediaPipe Hands
mp_hands = mp.solutions.hands
hands = mp_hands.Hands()
mp_draw = mp.solutions.drawing_utils

# Initialize video capture
cap = cv2.VideoCapture(0)

while True:
    success, img = cap.read()
    if not success:
        break

    # Convert the BGR image to RGB
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    
    # Process the image and find hands
    results = hands.process(img_rgb)
    
    # Draw hand landmarks
    if results.multi_hand_landmarks:
        for hand_landmarks in results.multi_hand_landmarks:
            mp_draw.draw_landmarks(img, hand_landmarks, mp_hands.HAND_CONNECTIONS)

    # Display the image
    cv2.imshow("Hand Landmarks", img)
    
    # Break the loop on pressing 'q'
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the capture and close windows
cap.release()
cv2.destroyAllWindows()

C:\Users\21ste\anaconda3\envs\ComputerVision\Lib\site-packages\google\protobuf\symbol_database.py:55: UserWarning: SymbolDatabase.GetPrototype() is deprecated. Please use message_factory.GetMessageClass() instead. SymbolDatabase.GetPrototype() will be removed soon.
  warnings.warn('SymbolDatabase.GetPrototype() is deprecated. Please '


In [4]:
if results.multi_hand_landmarks is not None:
    len(results.multi_hand_landmarks[0].landmark)

print(results.multi_hand_landmarks)

[landmark {
  x: 0.172768116
  y: 0.970387816
  z: 7.65904701e-007
}
landmark {
  x: 0.269867331
  y: 0.937782347
  z: -0.0329808667
}
landmark {
  x: 0.36486268
  y: 0.857812285
  z: -0.0415790305
}
landmark {
  x: 0.441080451
  y: 0.802101135
  z: -0.0497339889
}
landmark {
  x: 0.503159225
  y: 0.7745381
  z: -0.0562442206
}
landmark {
  x: 0.333742261
  y: 0.671423793
  z: 0.00840052497
}
landmark {
  x: 0.391335547
  y: 0.57624054
  z: 0.000256689498
}
landmark {
  x: 0.422877252
  y: 0.516356051
  z: -0.0154764093
}
landmark {
  x: 0.448996425
  y: 0.463596225
  z: -0.0288301148
}
landmark {
  x: 0.281427681
  y: 0.638478816
  z: 0.00676353462
}
landmark {
  x: 0.32194671
  y: 0.513248
  z: 0.00471798
}
landmark {
  x: 0.348638117
  y: 0.43202877
  z: -0.00964828
}
landmark {
  x: 0.37085855
  y: 0.364884824
  z: -0.0227040127
}
landmark {
  x: 0.224193767
  y: 0.633632123
  z: -0.00219762512
}
landmark {
  x: 0.256851405
  y: 0.517437935
  z: -0.0104285292
}
landmark {
  x: 0.28

In [3]:
hand = []
for res in results.multi_hand_landmarks[0].landmark:
    test = np.array([res.x, res.y, res.z])
    hand.append(test)

In [4]:
hand

[array([ 1.10653356e-01,  8.40650797e-01, -8.40775485e-08]),
 array([ 0.20370644,  0.90473753, -0.01758477]),
 array([ 0.29257888,  0.95954144, -0.04289951]),
 array([ 0.35290524,  0.96841967, -0.06817947]),
 array([ 0.3727107 ,  0.9155637 , -0.09315211]),
 array([ 0.32863402,  0.86786121, -0.0621929 ]),
 array([ 0.32942146,  0.99669838, -0.11100143]),
 array([ 0.29948169,  1.02702463, -0.1414241 ]),
 array([ 0.28835338,  1.00905561, -0.16078572]),
 array([ 0.28022093,  0.84379929, -0.07724471]),
 array([ 0.26927474,  1.00618064, -0.11555979]),
 array([ 0.2457993 ,  1.01944971, -0.12600937]),
 array([ 0.24227858,  0.98674631, -0.13737567]),
 array([ 0.22025311,  0.83392233, -0.09363868]),
 array([ 0.21779531,  0.975546  , -0.12973042]),
 array([ 0.19887239,  0.99522042, -0.12114286]),
 array([ 0.19034666,  0.97910684, -0.11610265]),
 array([ 0.15931553,  0.83199322, -0.11164748]),
 array([ 0.16810706,  0.94331467, -0.13925406]),
 array([ 0.15612237,  0.98078161, -0.13185044]),
 array([

In [3]:
def extract_keypoints(results):
    hand = np.array([[res.x, res.y, res.z] for res in results.multi_hand_landmarks[0].landmark]).flatten() if results.multi_hand_landmarks is not None else np.zeros(21 * 3)
    return hand

In [65]:
keypoints = extract_keypoints(results)
keypoints

array([ 5.72707832e-01,  7.82722890e-01, -1.50313284e-07,  6.25784099e-01,
        7.46695697e-01, -1.75854843e-02,  6.57452822e-01,  6.56242549e-01,
       -2.26993002e-02,  6.46410704e-01,  5.76803267e-01, -2.81400587e-02,
        6.07787967e-01,  5.37198544e-01, -3.07809506e-02,  6.51542723e-01,
        5.96962631e-01,  6.53833430e-03,  6.69347048e-01,  5.38327754e-01,
       -1.10745430e-02,  6.65272474e-01,  5.66038489e-01, -2.79365834e-02,
        6.55912220e-01,  6.00370944e-01, -3.74448411e-02,  6.19822383e-01,
        5.81488073e-01,  5.23557281e-03,  6.31226063e-01,  5.04891753e-01,
       -9.77924466e-03,  6.34571373e-01,  5.40347338e-01, -2.10995600e-02,
        6.29491627e-01,  5.78044951e-01, -2.54081301e-02,  5.86334288e-01,
        5.80359638e-01, -1.29718683e-04,  5.93971193e-01,  5.01294672e-01,
       -2.02827398e-02,  6.04824841e-01,  5.45495212e-01, -2.26862691e-02,
        6.00799322e-01,  5.86882055e-01, -1.96878370e-02,  5.50400257e-01,
        5.89041650e-01, -

In [4]:
# Path for exported data, numpy arrays
DATA_PATH = os.path.join('Num_Data') 

# Actions that we try to detect
actions = np.array(['1', '2', '3'])

# Thirty videos worth of data
no_sequences = 3

# Videos are going to be 30 frames in length
sequence_length = 30

In [5]:
for action in actions: 
    for sequence in range(no_sequences):
        try: 
            os.makedirs(os.path.join(DATA_PATH, action, str(sequence)))
        except Exception as e:
            print(e)

[WinError 183] Cannot create a file when that file already exists: 'Num_Data\\1\\0'
[WinError 183] Cannot create a file when that file already exists: 'Num_Data\\1\\1'
[WinError 183] Cannot create a file when that file already exists: 'Num_Data\\1\\2'
[WinError 183] Cannot create a file when that file already exists: 'Num_Data\\2\\0'
[WinError 183] Cannot create a file when that file already exists: 'Num_Data\\2\\1'
[WinError 183] Cannot create a file when that file already exists: 'Num_Data\\2\\2'
[WinError 183] Cannot create a file when that file already exists: 'Num_Data\\3\\0'
[WinError 183] Cannot create a file when that file already exists: 'Num_Data\\3\\1'
[WinError 183] Cannot create a file when that file already exists: 'Num_Data\\3\\2'


In [68]:
# Start capturing video
cap = cv2.VideoCapture(0)

while cap.isOpened():
    # NEW LOOP
    # Loop through actions
    for action in actions:
        # Loop through sequences aka videos
        for sequence in range(no_sequences):
            # Loop through video length aka sequence length
            for frame_num in range(sequence_length):

                # Read feed
                ret, image = cap.read()

                # Convert the BGR image to RGB
                img_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    
                # Process the image and find hands
                results = hands.process(img_rgb)

                # Draw hand landmarks
                if results.multi_hand_landmarks:
                    for hand_landmarks in results.multi_hand_landmarks:
                        mp_draw.draw_landmarks(img, hand_landmarks, mp_hands.HAND_CONNECTIONS)
                
                # NEW Apply wait logic
                if frame_num == 0: 
                    cv2.putText(image, 'STARTING COLLECTION', (120,200), 
                               cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255, 0), 4, cv2.LINE_AA)
                    cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    # Show to screen
                    cv2.imshow('OpenCV Feed', image)
                    cv2.waitKey(2000)
                else: 
                    cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    # Show to screen
                    cv2.imshow('OpenCV Feed', image)
                
                # NEW Export keypoints
                keypoints = extract_keypoints(results)
                npy_path = os.path.join(DATA_PATH, action, str(sequence), str(frame_num))
                np.save(npy_path, keypoints)

                # Break gracefully
                if cv2.waitKey(10) & 0xFF == ord('q'):
                    break
                    
    cap.release()
    cv2.destroyAllWindows()

C:\Users\21ste\anaconda3\envs\ComputerVision\Lib\site-packages\google\protobuf\symbol_database.py:55: UserWarning: SymbolDatabase.GetPrototype() is deprecated. Please use message_factory.GetMessageClass() instead. SymbolDatabase.GetPrototype() will be removed soon.
  warnings.warn('SymbolDatabase.GetPrototype() is deprecated. Please '


In [18]:

cap.release()
cv2.destroyAllWindows()

In [6]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [7]:
label_map = {label:num for num, label in enumerate(actions)}

In [8]:
label_map

{'1': 0, '2': 1, '3': 2}

In [9]:
res = np.load(os.path.join(DATA_PATH, '2', '1', "{}.npy".format(0)))
res

array([ 2.59274721e-01,  7.70590544e-01, -3.41027260e-07,  3.14576119e-01,
        7.45426059e-01, -2.00603362e-02,  3.67631406e-01,  6.64771438e-01,
       -3.02429739e-02,  3.63141805e-01,  5.87185323e-01, -4.03786749e-02,
        3.22023809e-01,  5.38140833e-01, -4.33878042e-02,  3.70929062e-01,
        5.44777393e-01, -2.98266043e-03,  3.91915143e-01,  5.12260795e-01,
       -3.70476730e-02,  3.76942247e-01,  5.78421831e-01, -5.49738742e-02,
        3.63274604e-01,  6.01919234e-01, -6.40371367e-02,  3.26797038e-01,
        5.23013532e-01, -9.81445052e-03,  3.43929201e-01,  4.94615167e-01,
       -4.56106775e-02,  3.40266258e-01,  5.67422390e-01, -5.41689619e-02,
        3.35127652e-01,  5.88014960e-01, -5.11386991e-02,  2.85688251e-01,
        5.26484251e-01, -2.28794869e-02,  3.03584933e-01,  5.49114108e-01,
       -5.90543114e-02,  3.08515340e-01,  6.21457040e-01, -5.81825934e-02,
        3.05206627e-01,  6.34098291e-01, -4.95626666e-02,  2.50952184e-01,
        5.48449814e-01, -

In [10]:
res = np.load(os.path.join(DATA_PATH, '1', '1', "{}.npy".format(1)))
res

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
sequences, labels = [], []
for action in actions:
    for sequence in np.array(os.listdir(os.path.join(DATA_PATH, action))).astype(int):
        window = []
        for frame_num in range(sequence_length):
            res = np.load(os.path.join(DATA_PATH, action, str(sequence), "{}.npy".format(frame_num)))
            #sequences.append(label_map[action])
            window.append(res)
        sequences.append(window)
        labels.append(label_map[action])

In [12]:
len(sequences)

9

In [13]:
np.array(sequences).shape

(9, 30, 63)

In [14]:
np.array(labels).shape

(9,)

In [15]:
X = np.array(sequences)

In [16]:
X.shape

(9, 30, 63)

In [17]:
y = to_categorical(labels).astype(int)

In [18]:
y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])

In [19]:
X = torch.from_numpy(X)
X = X.to(torch.float32)
y = torch.from_numpy(y)
y = y.to(torch.float32)

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05)

In [21]:
X_train[0].shape

torch.Size([30, 63])

In [22]:
X_train.shape

torch.Size([8, 30, 63])

In [26]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from torch.utils.tensorboard import SummaryWriter
import numpy as np

class LSTMModel(nn.Module):
    def __init__(self, input_size, hidden_size1, hidden_size2, hidden_size3, output_size):
        super(LSTMModel, self).__init__()
        
        self.lstm1 = nn.LSTM(input_size, hidden_size1, batch_first=True)
        self.lstm2 = nn.LSTM(hidden_size1, hidden_size2, batch_first=True)
        self.lstm3 = nn.LSTM(hidden_size2, hidden_size3, batch_first=True)
        
        self.fc1 = nn.Linear(hidden_size3, 64)
        self.fc2 = nn.Linear(64, 32)
        self.fc3 = nn.Linear(32, output_size)
        
        self.relu = nn.ReLU()
        self.softmax = nn.Softmax(dim=1)
        
    def forward(self, x):
        x, _ = self.lstm1(x)
        x = self.relu(x)
        
        x, _ = self.lstm2(x)
        x = self.relu(x)
        
        x, _ = self.lstm3(x)
        x = self.relu(x)
        
        # Take only the output of the last time step
        x = x[:, -1, :]
        
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.softmax(self.fc3(x))
        
        return x

# Assuming the input shape is (30, 1662) and actions.shape[0] is the number of classes
input_size = 63
hidden_size1 = 64
hidden_size2 = 128
hidden_size3 = 64
output_size = 3  # Replace this with the actual number of classes

In [ ]:


model = LSTMModel(input_size, hidden_size1, hidden_size2, hidden_size3, output_size)

# Define loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

dataset = TensorDataset(X, y)
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

train_losses = []

# Training loop
num_epochs = 200
for epoch in range(num_epochs):
    epoch_loss = 0
    for batch_idx, (inputs, targets) in enumerate(dataloader):
        optimizer.zero_grad()
        
        outputs = model(inputs)
        loss = criterion(outputs, targets)
        
        loss.backward()
        optimizer.step()

        epoch_loss += loss.item()
       
    average_epoch_loss = epoch_loss / len(dataloader)
    train_losses.append(average_epoch_loss)
    if epoch % 10 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

# Plot the training loss
plt.figure(figsize=(10, 5))
plt.plot(train_losses, label='Training Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training Loss over Epochs')
plt.legend()
plt.show()

# Save the model
torch.save(model.state_dict(), 'lstm_model.pth')

In [27]:
model = LSTMModel(input_size, hidden_size1, hidden_size2, hidden_size3, output_size)
model.load_state_dict(torch.load('lstm_model.pth'))

<All keys matched successfully>

In [28]:
res = model(X_train[0].unsqueeze(0))

In [29]:
res

tensor([[0.0012, 0.9977, 0.0011]], grad_fn=<SoftmaxBackward0>)

In [30]:
actions[torch.argmax(res)]

'2'

In [31]:
actions[torch.argmax(y_test[0])]

'3'

In [32]:
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score

In [33]:
yhat = model(X)

In [34]:
yhat

tensor([[9.9877e-01, 1.2263e-03, 2.4858e-09],
        [9.9878e-01, 1.2169e-03, 2.4326e-09],
        [9.9864e-01, 1.3568e-03, 3.1771e-09],
        [1.2058e-03, 9.9767e-01, 1.1277e-03],
        [1.2492e-03, 9.9770e-01, 1.0537e-03],
        [1.5947e-03, 9.9674e-01, 1.6687e-03],
        [1.9519e-07, 2.3335e-03, 9.9767e-01],
        [1.9498e-07, 2.3483e-03, 9.9765e-01],
        [2.1884e-07, 2.4322e-03, 9.9757e-01]], grad_fn=<SoftmaxBackward0>)

In [35]:
ytrue = torch.argmax(y, dim=1).tolist()
yhat = torch.argmax(yhat, dim=1).tolist()

In [36]:
yhat

[0, 0, 0, 1, 1, 1, 2, 2, 2]

In [37]:
ytrue

[0, 0, 0, 1, 1, 1, 2, 2, 2]

In [38]:
multilabel_confusion_matrix(ytrue, yhat)

array([[[6, 0],
        [0, 3]],

       [[6, 0],
        [0, 3]],

       [[6, 0],
        [0, 3]]], dtype=int64)

In [39]:
accuracy_score(ytrue, yhat)

1.0

In [40]:
from scipy import stats

In [41]:
colors = [(245,117,16), (117,245,16), (16,117,245)]
def prob_viz(res, actions, input_frame, colors):
    output_frame = input_frame.copy()
    for num, prob in enumerate(res):
        cv2.rectangle(output_frame, (0,60+num*40), (int(prob*100), 90+num*40), colors[num], -1)
        cv2.putText(output_frame, actions[num], (0, 85+num*40), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2, cv2.LINE_AA)
        
    return output_frame

In [42]:
plt.figure(figsize=(18,18))
plt.imshow(prob_viz(res, actions, image, colors))

NameError: name 'image' is not defined

<Figure size 1800x1800 with 0 Axes>

In [43]:
# 1. New detection variables
sequence = []
sentence = []
predictions = []
threshold = 0.5

cap = cv2.VideoCapture(0)
# Set mediapipe model 
while cap.isOpened():

    # Read feed
    ret, image = cap.read()

    # Convert the BGR image to RGB
    img_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Process the image and find hands
    results = hands.process(img_rgb)
    
    # Draw hand landmarks
    if results.multi_hand_landmarks:
        for hand_landmarks in results.multi_hand_landmarks:
            mp_draw.draw_landmarks(image, hand_landmarks, mp_hands.HAND_CONNECTIONS)
    
    # 2. Prediction logic
    keypoints = extract_keypoints(results)
    sequence.append(keypoints)
    sequence = sequence[-30:]
    
    if len(sequence) == 30:
        cSequence = torch.Tensor(sequence)
        res = model(cSequence.unsqueeze(0))[0]
        #print(res)
        #print(actions[np.argmax(res)])
        predictions.append(torch.argmax(res))
        
        
    #3. Viz logic
        if np.unique(predictions[-10:])[0]==torch.argmax(res): 
            if res[torch.argmax(res)] > threshold: 
                
                if len(sentence) > 0: 
                    if actions[torch.argmax(res)] != sentence[-1]:
                        sentence.append(actions[torch.argmax(res)])
                else:
                    sentence.append(actions[torch.argmax(res)])

        if len(sentence) > 5: 
            sentence = sentence[-5:]

        # Viz probabilities
        image = prob_viz(res, actions, image, colors)
        
    cv2.rectangle(image, (0,0), (640, 40), (245, 117, 16), -1)
    cv2.putText(image, ' '.join(sentence), (3,30), 
                   cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
    
    # Show to screen
    cv2.imshow('OpenCV Feed', image)

    # Break gracefully
    if cv2.waitKey(10) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

C:\Users\21ste\anaconda3\envs\ComputerVision\Lib\site-packages\google\protobuf\symbol_database.py:55: UserWarning: SymbolDatabase.GetPrototype() is deprecated. Please use message_factory.GetMessageClass() instead. SymbolDatabase.GetPrototype() will be removed soon.
  warnings.warn('SymbolDatabase.GetPrototype() is deprecated. Please '
C:\Users\21ste\AppData\Local\Temp\ipykernel_13876\2162121121.py:31: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ..\torch\csrc\utils\tensor_new.cpp:277.)
  cSequence = torch.Tensor(sequence)


In [63]:
cap.release()
cv2.destroyAllWindows()